<script setup lang="ts">
import { computed, ref } from 'vue';
import Icon from './Icon.vue';
import { formatTime, fallbackArtist } from '../features/format';
const props = defineProps<{ title?: string; artist?: string | null; playing: boolean; loading: boolean; position: number; duration?: number | null; volume: number; repeat: 'off' | 'one' | 'all'; target: 'discord' | 'browser'; canControl: boolean; canCancel: boolean; hasPrevious: boolean; queueCount: number; queueOpen: boolean; busy: boolean; urgentBusy: boolean; shuffled: boolean }>();
const emit = defineEmits<{ toggle: []; previous: []; next: []; restart: []; stop: []; seek: [seconds: number]; volume: [percent: number]; repeat: []; shuffle: []; queue: []; target: [value: 'discord' | 'browser'] }>();
const dragging = ref(false); const draftPosition = ref(0);
const seekable = computed(() => props.duration != null && props.duration > 0 && props.canControl);
const visiblePosition = computed(() => dragging.value ? draftPosition.value : props.position);
const cancelMode = computed(() => props.loading || (props.busy && !props.title));
function seek(event: Event) { dragging.value = false; emit('seek', Number((event.target as HTMLInputElement).value)); }
</script>
<template>
  <footer class="player-bar" aria-label="音樂播放器">
    <div class="now-playing"><span class="now-art" :class="{ active: playing }"><Icon name="music" :size="23" /><span v-if="playing" class="equalizer"><i></i><i></i><i></i></span></span><div class="truncate"><strong :title="title">{{ title || '準備聽點音樂？' }}</strong><span>{{ title ? fallbackArtist(artist) : '選擇一首歌曲，開始你的音樂時光' }}</span></div></div>
    <div class="player-center"><div class="transport"><button class="icon-button side-control" :class="{ enabled: shuffled }" :disabled="!canControl || busy" aria-label="隨機排列待播" :aria-pressed="shuffled" title="隨機排列待播" @click="emit('shuffle')"><Icon name="shuffle" :size="17" /></button><button class="icon-button" :disabled="!canControl || !hasPrevious || busy" aria-label="上一首" @click="emit('previous')"><Icon name="previous" :size="20" /></button><button class="main-play" :disabled="cancelMode ? !canCancel || urgentBusy : !canControl || !title || busy" :aria-label="cancelMode ? '停止載入' : playing ? '暫停' : '繼續播放'" @click="cancelMode ? emit('stop') : emit('toggle')"><Icon v-if="cancelMode" name="stop" :size="17" /><span v-else-if="busy" class="loading-ring"></span><Icon v-else :name="playing ? 'pause' : 'play'" :size="20" /></button><button class="icon-button" :disabled="!canCancel || (!title && !loading && !busy) || urgentBusy" aria-label="下一首" @click="emit('next')"><Icon name="next" :size="20" /></button><button class="icon-button side-control" :class="{ enabled: repeat !== 'off' }" :disabled="!canControl || busy" :aria-label="`循環模式：${repeat === 'one' ? '單曲' : repeat === 'all' ? '全部' : '關閉'}，按一下切換`" title="切換循環模式" @click="emit('repeat')"><Icon name="repeat" :size="17" /><span v-if="repeat === 'one'" class="repeat-one">1</span></button></div>
      <div class="progress-row"><span>{{ formatTime(visiblePosition) }}</span><input class="range progress" type="range" aria-label="播放進度" :disabled="!seekable || busy" min="0" :max="duration || 1" step="1" :value="visiblePosition" :style="{ '--fill': `${duration ? visiblePosition / duration * 100 : 0}%` }" @input="dragging = true; draftPosition = Number(($event.target as HTMLInputElement).value)" @change="seek" /><span>{{ formatTime(duration) }}</span></div>
    </div>
    <div class="player-extra"><button class="icon-button extra-control" :disabled="!canControl || !title || busy" aria-label="重播目前歌曲" title="重播" @click="emit('restart')"><Icon name="restart" :size="17" /></button><button class="icon-button extra-control" :disabled="!canCancel || (!title && !loading && !busy) || urgentBusy" aria-label="停止播放" title="停止播放" @click="emit('stop')"><Icon name="stop" :size="16" /></button><button class="device-indicator" :aria-label="target === 'discord' ? '切換到此瀏覽器播放' : '切換到 Discord 語音播放'" @click="emit('target', target === 'discord' ? 'browser' : 'discord')"><Icon :name="target === 'discord' ? 'discord' : 'browser'" :size="18" /><span>{{ target === 'discord' ? 'Discord' : '瀏覽器' }}</span></button><label class="volume-control"><Icon name="volume" :size="18" /><span class="sr-only">音量</span><input class="range" type="range" min="0" max="100" :value="volume" :disabled="!canControl || busy" :style="{ '--fill': `${volume}%` }" @change="emit('volume', Number(($event.target as HTMLInputElement).value))" /></label><button class="icon-button queue-toggle" :class="{ enabled: queueOpen }" aria-label="切換待播佇列" :aria-expanded="queueOpen" @click="emit('queue')"><Icon name="queue" :size="21" /><span v-if="queueCount" class="queue-number">{{ queueCount }}</span></button></div>
  </footer>
</template>
